[workspace]
members = [
    "actuators/chat/back",
    "actuators/chat/front",
    "actuators/chat/dto",
    "actuators/chat/macros",
    "infer/lib",
    "infer/macros",
]
resolver = "2"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
