apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: chat:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: INFER_URL
          value: "http://infer"
---
apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  type: ClusterIP
  selector:
    app: chat
  ports:
  - port: 8080
    targetPort: 8080 