apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-front
  labels:
    app: chat-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-front
  template:
    metadata:
      labels:
        app: chat-front
    spec:
      containers:
      - name: chat-front
        image: chat-front:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chat-front
spec:
  type: NodePort
  selector:
    app: chat-front
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 