[package]
name = "auth-back"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
dotenvy = { workspace = true }
tower-http = { workspace = true, features = ["cors"] }

[[bin]]
name = "auth"
path = "src/main.rs"
