apiVersion: apps/v1
kind: Deployment
metadata:
  name: infer
  labels:
    app: infer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infer
  template:
    metadata:
      labels:
        app: infer
    spec:
      containers:
      - name: infer
        image: infer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: infer-config
---
apiVersion: v1
kind: Service
metadata:
  name: infer
spec:
  type: ClusterIP
  selector:
    app: infer
  ports:
  - port: 80
    targetPort: 80 